import './globals.css'
import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import { Inter } from 'next/font/google'
import CustomNavbar from '@/components/CustomNavbar'
import Footer from '@/components/Footer';
import UserProvider from '@/context/UserProvider';
const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProvider>

          <ToastContainer />
          <CustomNavbar />
          {children }
          <Footer />


        </UserProvider>
      </body>
    </html>
  )
}
